### ISSUE TITLE
path.rb

### ISSUE THREAD

**Issue by StevenNunez** [learn-co-curriculum/ruby-oo-assessment#2]
This one needs a solution. Also, the code could be better.

The normalize_path method returns can return `nil`. We want a normalized, absolute path returned.

**Comment by AnnJohn** [comment]
I'm fairly certain this has been fixed:

```ruby
  def normalize_path
    "#{"#{Dir.pwd}/" if relative_path?}#{path}"
  end
```

Looks like it will always return a string.
